[package]
name = "norman-client"
version = "0.1.0"
authors = ["sasha"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sentry = "0.12.0"
rand = "0.5.5"